# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.6.1
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: s
author_name: s
cloud_provider: netlify
contract_name: auction
deployment_language: python
ide_vscode: true
preset_name: production
project_name: Auction
python_linter: ruff
use_dispenser: true
use_github_actions: true
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true

